# Vector

---

- 벡터는 숫자를 원소로 가지는 리스트(list) 또는 배열(array)입니다

- 벡터는 공간에서 한 점을 나타냅니다

- 벡터는 원점으로부터 상대적 위치를 표현합니다



---

-  벡터 연산

- 벡터에 숫자를 곱해주면 길이만 변합니다 : 스칼라 곱 

- 벡터끼리 같은 모양을 가지면(차원이 같으면) 덧셈, 뺄셈을 계산할 수 있습니다.

- 두 벡터의 덧셈은 다른 벡터로부터 상대적 위치이동을 표현합니다

- 벡터끼리 같은 모양을 가지면(차원이 같으면) 성분곱(Hadamard product)을 계산할 수 있다.

---

In [1]:
import numpy as np

x = np.array([1,7,2])
y = np.array([5,2,1])

In [2]:
x + y

array([6, 9, 3])

In [3]:
x - y

array([-4,  5,  1])

In [4]:
# 성분곱 (Hadamard product)
x * y

array([ 5, 14,  2])

---

# Norm

- 벡터의 노름(norm)은 원점에서부터의 거리 를 말합니다. (임의의 차원 d 에 대해 성립하는 것을 명심)

- L1-노름은 각 성분의 **변화량의 절대값** 을 모두 더 합니다.

- L2-노름은 **피타고라스 정리**를 이용해 유클리드 거리를 계산합니다

- 노름의 종류에 따라 기하학적 성질이 달라집니다, 각 성질들이 필요할 때가 있으므로 둘 다 사용 합니다.

---

In [7]:
def l1_norm(x):
    
    x_norm = np.abs(x) # 각 성분의 **변화량의 절대값**
    x_norm = np.sum(x_norm) # 모두 더 합니다.
    
    return x_norm

In [8]:
x = np.array([3,4])

In [9]:
l1_norm(x)

7

In [11]:
def l2_norm(x):
    
    x_norm = x*x # 1-1) 성분 곱
    
    x_norm = np.sum(x_norm) # 1-2) 더한 다음
    
    x_norm = np.sqrt(x_norm) # 1-3) 루트 
    
    return x_norm

In [12]:
l2_norm(x)

5.0

In [10]:
np.linalg.norm(x)

5.0

---

# 두 벡터 사이의 거리, 각도

- 두 벡터 사이의 거리를 계산할 때는 벡터의 뺄셈을 이용, |x-y| == |y-x| 

- 제2 코사인 법칙에 의해 두 벡터 사이의 각도

---

- 제2 코사인 법칙(The Second Law of Cosines)은 삼각학에서 사용되는 공식 중 하나로, 두 벡터 간의 각도를 계산하는 데 사용됩니다. 

- 특히, 두 벡터 A와 B 사이의 각도를 계산하는 데에 내적이 사용됩니다.

제2 코사인 법칙은 다음과 같이 표현됩니다:

\[||A - B||^2 = ||A||^2 + ||B||^2 - 2||A|| * ||B|| * \cos(\theta)\]

여기서,
- \(||A - B||\)는 벡터 A와 B 사이의 거리(norm)입니다.
- \(||A||\)는 벡터 A의 크기(norm)를 나타냅니다.
- \(||B||\)는 벡터 B의 크기(norm)를 나타냅니다.
- \(\theta\)는 A와 B 사이의 각도입니다.

이제 내적을 사용하여 이 공식을 유도해보겠습니다. 우선, 내적의 정의를 다시 상기해 봅시다.

두 벡터 A와 B의 내적은 다음과 같이 표현됩니다:

\[A \cdot B = ||A|| * ||B|| * \cos(\theta)\]

여기서,
- \(A \cdot B\)는 A와 B의 내적입니다.
- \(||A||\)는 벡터 A의 크기(norm)를 나타냅니다.
- \(||B||\)는 벡터 B의 크기(norm)를 나타냅니다.
- \(\theta\)는 A와 B 사이의 각도입니다.

이제 제2 코사인 법칙을 내적을 사용하여 표현해 봅시다. 우리는 벡터 A와 B 사이의 거리(norm)를 다음과 같이 정의할 수 있습니다:

\[||A - B|| = \sqrt{(A - B) \cdot (A - B)}\]

여기서, \((A - B) \cdot (A - B)\)는 벡터 (A - B)와 자기 자신의 내적을 나타냅니다.

제2 코사인 법칙의 공식에서 \(||A - B||^2\)을 \((A - B) \cdot (A - B)\)로 대체하면 다음과 같이 됩니다:

\[(A - B) \cdot (A - B) = ||A||^2 + ||B||^2 - 2||A|| * ||B|| * \cos(\theta)\]

여기서 우리는 벡터 A와 B 사이의 각도 \(\theta\)를 구할 수 있는데, 이 각도는 내적을 사용하여 계산한 것입니다. 이제 제2 코사인 법칙을 사용하여 두 벡터 사이의 각도 \(\theta\)를 구할 수 있습니다.


---

In [14]:
def angle(x ,y):
    
    v = np.inner(x, y) / (l2_norm(x) + l2_norm(y))

    theta = np.arccos(v)
    
    return theta

In [16]:
x = np.array([3,4])

y = np.array([1,0])

In [17]:
angle(x,y)

1.0471975511965976

---

# 벡터의 내적

- 내적은 정사영(orthogonal projection)된 벡터의 길이와 관련 있다.

- Proj(x) 의 길이는 코사인법칙에 의해 ∥x∥ cos θ 가 된다.

- 내적은 정사영의 길이를 벡터 y 의 길이 ∥y∥만큼 조정한 값이다.

- 내적은 두 벡터의 유사도(similarity)를 측정하는데 사용 가능하다.


---


## 두 벡터 사이의 거리 (Euclidean Distance)

두 벡터 A = (3, 4)와 B = (0, 0)의 거리를 계산해보겠습니다.

거리(A, B) = ||A - B|| = sqrt((3 - 0)^2 + (4 - 0)^2) = sqrt(9 + 16) = sqrt(25) = 5

따라서 벡터 A와 B 사이의 거리는 5입니다.

## 두 벡터 사이의 각도 (Angle Between Two Vectors)

두 벡터 A = (1, 2)와 B = (3, 1) 사이의 각도를 계산해보겠습니다.

먼저, A와 B의 내적을 계산합니다.

$A · B = (1 * 3) + (2 * 1) = 3 + 2 = 5$

그리고 A와 B의 크기를 계산합니다.

$||A|| = sqrt(1^2 + 2^2) = sqrt(1 + 4) = sqrt(5)$

$||B|| = sqrt(3^2 + 1^2) = sqrt(9 + 1) = sqrt(10)$

각도 θ를 구하기 위해 다음 공식을 사용합니다.

$cos(θ) = (A · B) / (||A|| * ||B||)$

$cos(θ) = 5 / (sqrt(5) * sqrt(10))$

$cos(θ) = 5 / (sqrt(5) * sqrt(10)) = 5 / (sqrt(50)) = sqrt(50) / 10$

이제 역코사인을 사용하여 각도 θ를 찾습니다.

$θ = acos(sqrt(50) / 10)$

약 1.107 라디안 또는 약 63.43도입니다.

## 제 2 코사인 법칙 (Law of Cosines)

이번에는 벡터 A = (1, 2)와 B = (3, 1)의 거리를 제 2 코사인 법칙을 사용하여 계산해보겠습니다. 위에서 내적과 크기는 이미 계산했습니다.

$||A - B||^2 = ||A||^2 + ||B||^2 - 2 * ||A|| * ||B|| * cos(θ)$

$||A - B||^2 = (sqrt(5))^2 + (sqrt(10))^2 - 2 * sqrt(5) * sqrt(10) * cos(θ)$

$||A - B||^2 = 5 + 10 - 2 * sqrt(50) * cos(θ)$

$||A - B||^2 = 15 - 10 * sqrt(2) * cos(θ)$

따라서 두 벡터 A와 B 사이의 거리의 제곱은 15 - 10 * sqrt(2) * cos(θ)입니다.

## 내적 (Dot Product)

벡터 A = (2, 3)와 벡터 B = (4, 1)의 내적을 계산해보겠습니다.

A · B = (2 * 4) + (3 * 1) = 8 + 3 = 11

따라서 벡터 A와 B의 내적은 11입니다.